// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: speech/v1/speech.proto

package speechv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// RecognizeRequest carries either the initial configuration or a chunk of audio.
// The first message on the stream MUST be a config; every subsequent message
// MUST be audio_content.
type RecognizeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Request:
	//
	//	*RecognizeRequest_Config
	//	*RecognizeRequest_AudioContent
	Request       isRecognizeRequest_Request `protobuf_oneof:"request"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeRequest) Reset() {
	*x = RecognizeRequest{}
	mi := &file_speech_v1_speech_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeRequest) ProtoMessage() {}

func (x *RecognizeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_speech_v1_speech_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeRequest.ProtoReflect.Descriptor instead.
func (*RecognizeRequest) Descriptor() ([]byte, []int) {
	return file_speech_v1_speech_proto_rawDescGZIP(), []int{0}
}

func (x *RecognizeRequest) GetRequest() isRecognizeRequest_Request {
	if x != nil {
		return x.Request
	}
	return nil
}

func (x *RecognizeRequest) GetConfig() *RecognitionConfig {
	if x != nil {
		if x, ok := x.Request.(*RecognizeRequest_Config); ok {
			return x.Config
		}
	}
	return nil
}

func (x *RecognizeRequest) GetAudioContent() []byte {
	if x != nil {
		if x, ok := x.Request.(*RecognizeRequest_AudioContent); ok {
			return x.AudioContent
		}
	}
	return nil
}

type isRecognizeRequest_Request interface {
	isRecognizeRequest_Request()
}

type RecognizeRequest_Config struct {
	Config *RecognitionConfig `protobuf:"bytes,1,opt,name=config,proto3,oneof"`
}

type RecognizeRequest_AudioContent struct {
	// audio_content is little-endian 16-bit PCM, single channel, at the
	// sample rate declared in the config.
	AudioContent []byte `protobuf:"bytes,2,opt,name=audio_content,json=audioContent,proto3,oneof"`
}

func (*RecognizeRequest_Config) isRecognizeRequest_Request() {}

func (*RecognizeRequest_AudioContent) isRecognizeRequest_Request() {}

// RecognitionConfig declares the format of the audio that follows.
type RecognitionConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// sample_rate_hertz is the sampling rate of audio_content, e.g. 16000.
	// When zero, the server's default sample rate is used.
	SampleRateHertz int32 `protobuf:"varint,1,opt,name=sample_rate_hertz,json=sampleRateHertz,proto3" json:"sample_rate_hertz,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RecognitionConfig) Reset() {
	*x = RecognitionConfig{}
	mi := &file_speech_v1_speech_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognitionConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognitionConfig) ProtoMessage() {}

func (x *RecognitionConfig) ProtoReflect() protoreflect.Message {
	mi := &file_speech_v1_speech_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognitionConfig.ProtoReflect.Descriptor instead.
func (*RecognitionConfig) Descriptor() ([]byte, []int) {
	return file_speech_v1_speech_proto_rawDescGZIP(), []int{1}
}

func (x *RecognitionConfig) GetSampleRateHertz() int32 {
	if x != nil {
		return x.SampleRateHertz
	}
	return 0
}

// RecognizeResponse is a single transcription result.
type RecognizeResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// text is the recognized transcript for the current utterance.
	Text string `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	// is_final reports whether text is a finalized result (true) or an
	// in-progress partial hypothesis (false).
	IsFinal       bool `protobuf:"varint,2,opt,name=is_final,json=isFinal,proto3" json:"is_final,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecognizeResponse) Reset() {
	*x = RecognizeResponse{}
	mi := &file_speech_v1_speech_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecognizeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecognizeResponse) ProtoMessage() {}

func (x *RecognizeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_speech_v1_speech_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecognizeResponse.ProtoReflect.Descriptor instead.
func (*RecognizeResponse) Descriptor() ([]byte, []int) {
	return file_speech_v1_speech_proto_rawDescGZIP(), []int{2}
}

func (x *RecognizeResponse) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *RecognizeResponse) GetIsFinal() bool {
	if x != nil {
		return x.IsFinal
	}
	return false
}

var File_speech_v1_speech_proto protoreflect.FileDescriptor

const file_speech_v1_speech_proto_rawDesc = "" +
	"\n" +
	"\x16speech/v1/speech.proto\x12\tspeech.v1\"|\n" +
	"\x10RecognizeRequest\x126\n" +
	"\x06config\x18\x01 \x01(\v2\x1c.speech.v1.RecognitionConfigH\x00R\x06config\x12%\n" +
	"\raudio_content\x18\x02 \x01(\fH\x00R\faudioContentB\t\n" +
	"\arequest\"?\n" +
	"\x11RecognitionConfig\x12*\n" +
	"\x11sample_rate_hertz\x18\x01 \x01(\x05R\x0fsampleRateHertz\"B\n" +
	"\x11RecognizeResponse\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04text\x12\x19\n" +
	"\bis_final\x18\x02 \x01(\bR\aisFinal2_\n" +
	"\x11SpeechRecognition\x12J\n" +
	"\tRecognize\x12\x1b.speech.v1.RecognizeRequest\x1a\x1c.speech.v1.RecognizeResponse(\x010\x01B8Z6speech-recognition/internal/genproto/speechv1;speechv1b\x06proto3"

var (
	file_speech_v1_speech_proto_rawDescOnce sync.Once
	file_speech_v1_speech_proto_rawDescData []byte
)

func file_speech_v1_speech_proto_rawDescGZIP() []byte {
	file_speech_v1_speech_proto_rawDescOnce.Do(func() {
		file_speech_v1_speech_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_speech_v1_speech_proto_rawDesc), len(file_speech_v1_speech_proto_rawDesc)))
	})
	return file_speech_v1_speech_proto_rawDescData
}

var file_speech_v1_speech_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_speech_v1_speech_proto_goTypes = []any{
	(*RecognizeRequest)(nil),  // 0: speech.v1.RecognizeRequest
	(*RecognitionConfig)(nil), // 1: speech.v1.RecognitionConfig
	(*RecognizeResponse)(nil), // 2: speech.v1.RecognizeResponse
}
var file_speech_v1_speech_proto_depIdxs = []int32{
	1, // 0: speech.v1.RecognizeRequest.config:type_name -> speech.v1.RecognitionConfig
	0, // 1: speech.v1.SpeechRecognition.Recognize:input_type -> speech.v1.RecognizeRequest
	2, // 2: speech.v1.SpeechRecognition.Recognize:output_type -> speech.v1.RecognizeResponse
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_speech_v1_speech_proto_init() }
func file_speech_v1_speech_proto_init() {
	if File_speech_v1_speech_proto != nil {
		return
	}
	file_speech_v1_speech_proto_msgTypes[0].OneofWrappers = []any{
		(*RecognizeRequest_Config)(nil),
		(*RecognizeRequest_AudioContent)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_speech_v1_speech_proto_rawDesc), len(file_speech_v1_speech_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_speech_v1_speech_proto_goTypes,
		DependencyIndexes: file_speech_v1_speech_proto_depIdxs,
		MessageInfos:      file_speech_v1_speech_proto_msgTypes,
	}.Build()
	File_speech_v1_speech_proto = out.File
	file_speech_v1_speech_proto_goTypes = nil
	file_speech_v1_speech_proto_depIdxs = nil
}
