// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: speech/v1/speech.proto

package speechv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SpeechRecognition_Recognize_FullMethodName = "/speech.v1.SpeechRecognition/Recognize"
)

// SpeechRecognitionClient is the client API for SpeechRecognition service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// SpeechRecognition transcribes streamed PCM audio into text in real time.
type SpeechRecognitionClient interface {
	// Recognize is a bidirectional stream: the client sends a configuration
	// message followed by audio frames, and the server streams back partial and
	// final transcription results as they become available.
	Recognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse], error)
}

type speechRecognitionClient struct {
	cc grpc.ClientConnInterface
}

func NewSpeechRecognitionClient(cc grpc.ClientConnInterface) SpeechRecognitionClient {
	return &speechRecognitionClient{cc}
}

func (c *speechRecognitionClient) Recognize(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &SpeechRecognition_ServiceDesc.Streams[0], SpeechRecognition_Recognize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[RecognizeRequest, RecognizeResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeechRecognition_RecognizeClient = grpc.BidiStreamingClient[RecognizeRequest, RecognizeResponse]

// SpeechRecognitionServer is the server API for SpeechRecognition service.
// All implementations must embed UnimplementedSpeechRecognitionServer
// for forward compatibility.
//
// SpeechRecognition transcribes streamed PCM audio into text in real time.
type SpeechRecognitionServer interface {
	// Recognize is a bidirectional stream: the client sends a configuration
	// message followed by audio frames, and the server streams back partial and
	// final transcription results as they become available.
	Recognize(grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]) error
	mustEmbedUnimplementedSpeechRecognitionServer()
}

// UnimplementedSpeechRecognitionServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSpeechRecognitionServer struct{}

func (UnimplementedSpeechRecognitionServer) Recognize(grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]) error {
	return status.Errorf(codes.Unimplemented, "method Recognize not implemented")
}
func (UnimplementedSpeechRecognitionServer) mustEmbedUnimplementedSpeechRecognitionServer() {}
func (UnimplementedSpeechRecognitionServer) testEmbeddedByValue()                           {}

// UnsafeSpeechRecognitionServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SpeechRecognitionServer will
// result in compilation errors.
type UnsafeSpeechRecognitionServer interface {
	mustEmbedUnimplementedSpeechRecognitionServer()
}

func RegisterSpeechRecognitionServer(s grpc.ServiceRegistrar, srv SpeechRecognitionServer) {
	// If the following call pancis, it indicates UnimplementedSpeechRecognitionServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SpeechRecognition_ServiceDesc, srv)
}

func _SpeechRecognition_Recognize_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(SpeechRecognitionServer).Recognize(&grpc.GenericServerStream[RecognizeRequest, RecognizeResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type SpeechRecognition_RecognizeServer = grpc.BidiStreamingServer[RecognizeRequest, RecognizeResponse]

// SpeechRecognition_ServiceDesc is the grpc.ServiceDesc for SpeechRecognition service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SpeechRecognition_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "speech.v1.SpeechRecognition",
	HandlerType: (*SpeechRecognitionServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Recognize",
			Handler:       _SpeechRecognition_Recognize_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "speech/v1/speech.proto",
}
